name: platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform:
          [
            ubuntu-latest,
            ubuntu-20.04,
            ubuntu-18.04,
            macos-latest,
            macos-11,
            macOS-10.15,
            windows-latest,
            windows-2019,
          ]
          # os.arch:amd64,x86_64
          # os.name: Linux, Mac OS X,Windows Server 2022,Windows Server 2019
          # RUNNER_ARCH	执行作业的运行器的体系结构。 可能的值为 X86、X64、ARM 或 ARM64。
        arch: [x86, x64, arm, arm64]
    runs-on: ${{ matrix.platform }}
    RUNNER_ARCH: ${{ matrix.arch }}
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          #cache: gradle

      - name: build and run
        shell: bash
        continue-on-error: true
        run: |
          javac Tx.java
          echo "编译完成。。。。查看文件列表。。。。"
          ls -la
          java Tx
