name: platforms

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  # workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        platform:
          [
            ubuntu-latest,
            ubuntu-22.04,
            ubuntu-20.04,
            ubuntu-18.04,
            macos-latest,
            macos-12,
            macos-11,
            macOS-10.15,
            windows-latest,
            windows-2022,
            windows-2019,
          ]
          # os.arch:amd64,x86_64
          # os.name: Linux, Mac OS X,Windows Server 2022,Windows Server 2019
        # arch: [x86, x64, arm, arm64]
        include:
          - platform: "x86_64"
          - platform: "x86"
          - platform: "arm"
          - platform: "amd64"
        fail-fast: false

    runs-on: ${{ matrix.platform }}
    # RUNNER_ARCH: ${{ matrix.arch }}
    # runs-arch: x86
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          #cache: gradle

      - name: get all system envs
        shell: bash
        continue-on-error: true
        run: |
          javac SystemEnv.java
          echo "编译完成。。。。查看文件列表。。。。"
          ls -la
          java SystemEnv

      - name: get system info
        shell: bash
        continue-on-error: true
        run: |
          javac SystemInfo.java
          echo "编译完成。。。。查看文件列表。。。。"
          ls -la
          java SystemInfo
